---
title: "Homework 4"
author: "Lindsey Carlson"
date: "2/9/2022"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---


Question 1 
```{r}
x <- 1.1
a <- 2.2
b <- 3.3

#1a
z <- x^(a^b)
print(z)

#1b
z <- (x^a)^b
print(z)

#1c
z <- 3*(x^3) + 2*(x^2) + 1
print(z)
```

Question 2 
```{r}
#2a
Q2a <- c((seq(from=1, to = 8, by= )),(seq(from=7, to=1, by=-1)))
print(Q2a)

#2b
Q2b <- c(rep(1,1), rep(2,2), rep(3,3), rep(4,4), rep(5,5))
print(Q2b)

#2c
Q2c <- c(rep(5,1), rep(4,2), rep(3,3), rep(2,4), rep(1,5))
print(Q2c)
```

Question 3
```{r}
#Creating vector of two random uniform numbers
x <- c(runif(1))
y <- c(runif(1))
print(x)
print(y)

#Conversion of numbers to polar coordinates
r <- c(sqrt((x^2)+(y^2)))
theta <- c(atan(y/x))
print(r)
print(theta)
```

Question 4
```{r}
#Starting Sequence
queue <- c("sheep", "fox", "owl", "ant")
queue

#Q4a - serpent joins end of line
queue <- append(queue, "serpent")
queue

#Q4b - sheep enters ark
queue <- queue[-1]
queue

#Q4c - donkey arrives and goes to front
queue <- append(queue, "donkey", after=0)
queue

#Q4d - serpent leaves
queue <- queue[-5]
queue

#Q4e - owl leaves
queue<- queue[-3]
queue

#Q4f - aphid goes infront of ant
queue <- append(queue, "aphid", after=2)
queue

#Q4g
  #The aphid is third in line! 
```

Question 5
```{r}
Q5 <- c(1:100)
Q5 <- Q5[Q5 %% 3 != 0 & Q5 %% 7 != 0 & Q5 %% 2 != 0]

Q5
```

[Home Page](index.html)
